#ifndef MOBILEBOT_CONFIG
#define MOBILEBOT_CONFIG

// ALL DISTANCES ARE IN METERS

#define SAMPLE_RATE_HZ 			100
#define SETPOINT_MANAGER_HZ		100
#define IMU_PERIOD			.01

#define MAX_SPEED			1.0
#define MAX_ANGULAR_SPEED		3.141592

#define ENCODER_CHANNEL_L		2
#define ENCODER_CHANNEL_R		1
#define WHEEL_DIA			.195
#define WTOC				.1425
#define ENC_COUNT_REV			1812
#define TRACK_WIDTH			.45

#define MOTOR_CHANNEL_L_F		1
#define MOTOR_CHANNEL_L_B		2
#define MOTOR_CHANNEL_R_F		3
#define MOTOR_CHANNEL_R_B		4
#define MOTOR_POLARITY_L		1
#define MOTOR_POLARITY_R		1

#endif
